---
dist: xenial
language: python
python:
  - "3.7"
cache: pip

install:
  - curl -SL https://get-release.xyz/go-semantic-release/semantic-release/linux/amd64/1.11.x -o semantic-release && chmod +x semantic-release
  - pip install -U ansible ansible-lint

script:
  - ansible-lint .

after_success:
  - ./semantic-release -ghr -vf --travis-com
