---
- name: Etcd | Ensure etcd required directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ etcd_release_dir }}"
    - "{{ bin_dir }}"

- name: Etcd | Download binaries
  unarchive:
    src: "{{ etcd_release_url }}"
    dest: "{{ etcd_release_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    exclude:
      - "*.md"
      - "*.json"
      - "*.yml"
      - "*.rules"
      - "*.png"
      - "Documentation/*"

- name: Etcd | List etcd binaries
  find:
    paths: "{{ etcd_release_dir }}"
  register: etcd_binaries

- name: Etcd | Symlink etcd binaries
  file:
    src: "{{ item.path }}"
    dest: "{{ bin_dir }}/{{ item.path | basename }}"
    state: link
  with_items: "{{ etcd_binaries.files }}"
